server:
  port: 7777

logging:
  level:
    org:
      springframework:
        boot: INFO
    pl:
      project:
        invoicing: INFO
        invoicing.db: DEBUG

spring:
  profiles:
    active: file
  flyway:
    enabled: false
  security:
    name: piotr
    password: projekt

invoicing-system:
  allowedOrigins: http://localhost:4200
  csrf:
    disable: true
