server:
  port: 6666

invoicing-system:
  database: memory
  database.directory: db
  database.invoices.file: invoices.txt
  database.id.file: id.txt

  logging:
    level:
      org:
        springframework:
          boot: INFO
      pl:
        project:
          invoicing: INFO
          invoicing.db: DEBUG