spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicing-test
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true

invoicing-system:
  database: sql