server:
  port: 7777

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/invoicing
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher

invoicing-system:
  database: memory
  database.directory: db
  database.invoices.file: invoices.txt
  database.id.file: id.txt